### ISSUE TITLE
Error with the Catalyzation_Chamber's Property Direction

### ISSUE THREAD

**Issue by WolfBV** [daedalus4096/ThaumicWonders#25]
Yo, not sure if this is the right place to put this with the mods I have, also not sure if the error stuff I'm about to paste is enough, but when using NEI/JEI with this mod and grabbing a stack of wood in creative, the game freezes up for a bit and I get this error multiple times in the console

[NEI Item Loading/ERROR] [thaumicwonders]: Catching
java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to down on block thaumicwonders:catalyzation_chamber, it is not an allowed value
	at pl.asie.foamfix.common.FoamyBlockState.withProperty(FoamyBlockState.java:59) ~[foamfix-0.10.5-1.12.2.jar:?]
	at com.verdantartifice.thaumicwonders.common.blocks.base.BlockDeviceTW.getStateFromMeta(BlockDeviceTW.java:81) [BlockDeviceTW.class:?]
	at com.raoulvdberge.refinedstorage.apiimpl.network.node.cover.CoverManager.getBlockState(CoverManager.java:193) [CoverManager.class:?]
	at com.raoulvdberge.refinedstorage.apiimpl.network.node.cover.CoverManager.isValidCover(CoverManager.java:155) [CoverManager.class:?]
	at com.raoulvdberge.refinedstorage.item.ItemCover.getSubItems(ItemCover.java:119) [ItemCover.class:?]
	at codechicken.nei.util.ItemList$1.execute(ItemList.java:225) [ItemList$1.class:?]
	at codechicken.lib.thread.RestartableTask$1.run(RestartableTask.java:32) [RestartableTask$1.class:?]

**Comment by daedalus4096** [comment]
I wasn't able to reproduce the game freeze, but those exceptions should be squashed in the next release.
