### ISSUE TITLE
Panacea can't cure Thaumorrhea on dedicated server, kicks you instead

### ISSUE THREAD

**Issue by katzenpapst** [daedalus4096/ThaumicWonders#62]
Got Thaumorrhea (and Flux Flu, because you always get that, too), and wanted to eat a (regular, not enchanted) Panacea to cure it. Got kicked from the server instead.

The server's log said this:
```
[02:30:40] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /93.104.99.168:49416
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_201]
        at java.util.HashMap$ValueIterator.next(HashMap.java:1474) ~[?:1.8.0_201]
        at com.verdantartifice.thaumicwonders.common.items.consumables.ItemPanacea.func_77849_c(ItemPanacea.java:66) ~[ItemPanacea.class:?]
        at net.minecraft.item.ItemFood.func_77654_b(SourceFile:46) ~[aij.class:?]
        at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:222) ~[aip.class:?]
        at net.minecraft.entity.EntityLivingBase.func_71036_o(EntityLivingBase.java:2789) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71036_o(EntityPlayerMP.java:1125) ~[oq.class:?]
        at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2688) ~[vp.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2097) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
        ... 9 more
```

server: forge-1.12.2-14.23.5.2838-universal.jar

mod list: https://pastebin.com/nLTGVZ9K

**Comment by daedalus4096** [comment]
Thank you for reporting this issue.  It should now be fixed in version 1.8.2.
